// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entities.Migrations
{
    [DbContext(typeof(RepoContext))]
    [Migration("20210218105324_initial-migration-with-data")]
    partial class initialmigrationwithdata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<int>("FloorNo")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumOfRooms")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("Square")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Apartments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "New apartment with furniture",
                            FloorNo = 3,
                            ImageURL = "https://img01.cdnbor.uz/storage/uploads/listing_image/2020/09/07/4796303/200x160_fitted/358a23bec1b8765e7d996b8709c1d7bc.jpg",
                            NumOfRooms = 3,
                            Price = 450.0,
                            RegionId = 1,
                            Square = 85,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "New apartment with furniture, TV and internet (students pls don't bother)",
                            FloorNo = 2,
                            ImageURL = "https://img07.cdnbor.uz/storage/uploads/listing_image/2020/08/20/4750987/200x160_fitted/8d56f14d874026ea7372fcd5ef38d0fa.jpg",
                            NumOfRooms = 3,
                            Price = 500.0,
                            RegionId = 1,
                            Square = 80,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "apartment with furniture and TV (students pls don't bother)",
                            FloorNo = 2,
                            ImageURL = "https://img09.cdnbor.uz/storage/uploads/listing_image/2020/12/19/5019614/1920x1080_resized/97a0ae6b2446f4c8f5a6e84e36e9f2e9.jpeg",
                            NumOfRooms = 1,
                            Price = 300.0,
                            RegionId = 1,
                            Square = 35,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "there are some old furniture in the apartment",
                            FloorNo = 1,
                            ImageURL = "https://img02.cdnbor.uz/storage/uploads/listing_image/2019/09/11/4093722/200x160_fitted/1bd6f2237bd96f65d11dd3d5e34bec23.jpg",
                            NumOfRooms = 2,
                            Price = 35000.0,
                            RegionId = 1,
                            Square = 50,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            Description = "in good condition",
                            FloorNo = 3,
                            ImageURL = "https://img02.cdnbor.uz/storage/uploads/listing_image/2020/01/12/4337545/200x160_fitted/9ad824a18ce345550290c6c8783238e7.jpg",
                            NumOfRooms = 2,
                            Price = 40000.0,
                            RegionId = 1,
                            Square = 60,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            Description = "For Sale asap",
                            FloorNo = 1,
                            ImageURL = "https://img07.cdnbor.uz/storage/uploads/listing_image/2019/09/06/4082046/200x160_fitted/5046b9d8413f72a3aad412db0fb7b737.jpg",
                            NumOfRooms = 1,
                            Price = 25000.0,
                            RegionId = 1,
                            Square = 30,
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            Description = "in a good condition",
                            FloorNo = 9,
                            ImageURL = "https://img10.cdnbor.uz/storage/uploads/listing_image/2020/05/12/4533019/200x160_fitted/875eca3baaa10acde1afffa1d607a4ad.JPEG",
                            NumOfRooms = 1,
                            Price = 250.0,
                            RegionId = 1,
                            Square = 35,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "in a perfect condition",
                            FloorNo = 2,
                            ImageURL = "https://img06.cdnbor.uz/storage/uploads/listing_image/2021/01/03/5045061/200x160_fitted/a84ff6a169af313c467e8776b06f9abf.jpg",
                            NumOfRooms = 3,
                            Price = 55000.0,
                            RegionId = 1,
                            Square = 90,
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            Description = "apartment is for a long term rent only with contract",
                            FloorNo = 1,
                            ImageURL = "https://img06.cdnbor.uz/storage/uploads/listing_image/2021/02/18/5156013/200x160_fitted/f163967240f8715cbd98716b2f1118db.jpg",
                            NumOfRooms = 2,
                            Price = 1000.0,
                            RegionId = 1,
                            Square = 30,
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            Description = "Apartment with 4 bedrooms in a perfect condition in city center",
                            FloorNo = 3,
                            ImageURL = "https://img03.cdnbor.uz/storage/uploads/listing_image/2019/12/08/4282198/200x160_fitted/ca01a8611542d5a240e8c1870523195b.jpg",
                            NumOfRooms = 4,
                            Price = 100000.0,
                            RegionId = 1,
                            Square = 100,
                            Status = 0
                        });
                });

            modelBuilder.Entity("Entities.Models.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumOfRooms")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("Square")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Houses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "a cool place",
                            ImageURL = "https://img02.cdnbor.uz/storage/uploads/listing_image/2021/02/13/5143259/200x160_fitted/d105b6e989b550fc0ca7d982c25a690f.jpg",
                            NumOfRooms = 5,
                            Price = 1200.0,
                            RegionId = 1,
                            Square = 160,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "house for sale asap",
                            ImageURL = "https://img04.cdnbor.uz/storage/uploads/listing_image/2021/02/18/5156017/200x160_fitted/998df78b70a2fc148ac91ef55e5a6c3c.jpg",
                            NumOfRooms = 4,
                            Price = 110000.0,
                            RegionId = 1,
                            Square = 150,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "good house",
                            ImageURL = "https://img05.cdnbor.uz/storage/uploads/listing_image/2020/11/04/4920470/200x160_fitted/80d9206c5310864f26ff35978735ca56.jpg",
                            NumOfRooms = 5,
                            Price = 1500.0,
                            RegionId = 1,
                            Square = 185,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "in a good condition ",
                            ImageURL = "https://img10.cdnbor.uz/storage/uploads/listing_image/2020/11/04/4920442/200x160_fitted/c09510779675298b4afba809e48e63ca.jpg",
                            NumOfRooms = 5,
                            Price = 111200.0,
                            RegionId = 1,
                            Square = 190,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            Description = "something should've been written here so I wrote",
                            ImageURL = "https://img09.cdnbor.uz/storage/uploads/listing_image/2020/07/10/4672481/200x160_fitted/14cc822dbc2c8830c5d0a7b3b0675ea1.jpg",
                            NumOfRooms = 5,
                            Price = 1200.0,
                            RegionId = 1,
                            Square = 200,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "some description",
                            ImageURL = "https://img05.cdnbor.uz/storage/uploads/listing_image/2021/01/07/5055201/200x160_fitted/1675204b7ee8bab5877e853e657f0e5c.jpg",
                            NumOfRooms = 4,
                            Price = 120000.0,
                            RegionId = 1,
                            Square = 165,
                            Status = 0
                        });
                });

            modelBuilder.Entity("Entities.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tashkent"
                        });
                });

            modelBuilder.Entity("Entities.Models.Apartment", b =>
                {
                    b.HasOne("Entities.Models.Region", "Region")
                        .WithMany("Apartments")
                        .HasForeignKey("RegionId");
                });

            modelBuilder.Entity("Entities.Models.House", b =>
                {
                    b.HasOne("Entities.Models.Region", "Region")
                        .WithMany("Houses")
                        .HasForeignKey("RegionId");
                });
#pragma warning restore 612, 618
        }
    }
}
